raw <- read_csv("./data/elixir-ecosystem-survey-2020-raw-data.csv", col_types = cols(.default = "c"))

qs <- c(
  "Are you actively using Elixir in either professional or personal projects?",
  "Can you share why you stopped using or never used Elixir?",
  "What solutions was the Elixir ecosystem lacking?",
  "Which language did you change to?",
  "How long have you been using Elixir?",
  "What is the most recent version of Elixir that you have used?",
  "How did you first learn about Elixir?",
  "What sources of information was most impactful for learning Elixir?",
  "Have you written any Erlang?",
  "Have you written in any other BEAM based language?",
  "What is your age range?",
  "Which gender do you identify as?",
  "In which country do you currently reside?",
  "Do you have a college degree in Computer Science or similar degree?",
  "What part of Elixir did you find most difficult to learn?",
  "Do you maintain any Open Source (OSS) Elixir libraries?",
  "Have you made contributions to anyone else's OSS Elixir libraries?",
  "Have you made OSS contributions back to Elixir?",
  "How often do you attend local Elixir meetups?",
  "Do you help organize Elixir meetups?",
  "Do you attend your continent's major Elixir Conference",
  "Do you attend any regional Elixir/Erlang conferences?",
  "Do you participate in any online Elixir chats?",
  "Which Elixir Podcasts do you listen to?",
  "Which Elixir newsletters are you subscribed to?",
  "What industry is your company in?",
  "What is your role within your company?",
  "Does your company use Elixir?",
  "How long has your company been using Elixir?",
  "In what capacities is your company using Elixir?",
  "How many engineers are using Elixir at your company?",
  "Did your company migrate from another language or choose Elixir for a new project?",
  "Did your company migrate from another language / framework?",
  "What outcomes did your team experience after adopting Elixir?",
  "Which reasons prevented Elixir from being adopted at your company?",
  "Can you say which language(s) and describe why it won?",
  "Which operating system do you primarily develop on?",
  "Which editor/IDE do you primarily write Elixir with?",
  "How do you debug?",
  "Which operating system do you deploy to?",
  "What database do you primarily use?",
  "Do you write tests?",
  "Have you ever used Hot Code Reloading in production?",
  "Where do you deploy your Elixir applications to?",
  "How are you deploying your Elixir application?",
  "If your project(s) uses Continuous Integration which is it?",
  "If your team is enforcing code formatting what methods do you use?",
  "If there is one library that you are excited about in 2020 which is it?",
  "Are you using Phoenix?",
  "What is the most recent version of Phoenix that you have used?",
  "Are you running Phoenix in production?",
  "How are you using Phoenix?",
  "Are you using Nerves?",
  "What is the most recent version of Nerves that you have used?",
  "Are you using Scenic?",
  "Is your Nerves application distributed across many devices?"
)

questions <- tibble(id = seq_along(qs), question = qs)