raw <- read_csv("./data/elixir-ecosystem-survey-2020-raw-data.csv", col_types = cols(.default = "c"))

qs <- c(
  "Are you actively using Elixir in either professional or personal projects?",
  "What solutions was the Elixir ecosystem lacking?",
  "How long have you been using Elixir?",
  "What is the most recent version of Elixir that you have used?",
  "Have you written any Erlang?",
  "What is your age range?",
  "Which gender do you identify as?",
  "In which country do you currently reside?",
  "Do you have a college degree in Computer Science or similar degree?",
  "What part of Elixir did you find most difficult to learn?",
  "Do you maintain any Open Source (OSS) Elixir libraries?",
  "Have you made contributions to anyone else's OSS Elixir libraries?",
  "Have you made OSS contributions back to Elixir?",
  "How often do you attend local Elixir meetups?",
  "Do you help organize Elixir meetups?",
  "Do you attend your continent's major Elixir Conference",
  "Do you attend any regional Elixir/Erlang conferences?",
  "What industry is your company in?",
  "What is your role within your company?",
  "Does your company use Elixir?",
  "How long has your company been using Elixir?",
  "How many engineers are using Elixir at your company?",
  "Did your company migrate from another language or choose Elixir for a new project?",
  "Can you say which language(s) and describe why it won?",
  "Which operating system do you primarily develop on?",
  "Which editor/IDE do you primarily write Elixir with?",
  "Which operating system do you deploy to?",
  "Have you ever used Hot Code Reloading in production?",
  "If there is one library that you are excited about in 2020 which is it?",
  "Are you using Phoenix?",
  "What is the most recent version of Phoenix that you have used?",
  "Are you running Phoenix in production?",
  "Are you using Nerves?",
  "What is the most recent version of Nerves that you have used?",
  "Are you using Scenic?",
  "Is your Nerves application distributed across many devices?",
  "What tool do you use to format code?",
  "What CI/CD tool do you use?",
  "How do you deploy Elixir in production?",
  "What platform do you use to deploy your code in production?",
  "What database do you most often use with Elixir?",
  "What tool do you most often use to debug Elixir code?",
  "What were challenges to adopting Elixir for your team?",
  "What benefits did your team experience by using Elixir?",
  "In what capacities is your company using Elixir?",
  "Do you subscribe to any Elixir newsletters?",
  "Do you listen to any Elixir podcasts?",
  "Do you participate in any Elixir forums or communities?",
  "How do you prefer to learn a new language?",
  "How were you first introduced to Elixir?",
  "What language were you using prior to Elixir?"
)

questions <- tibble(id = seq_along(qs), question = qs)